openapi: 3.0.1

info:
  title: Chatgpt plugin ToDo list
  version: 1.0.0
  description: API for managing a todo list

paths:
  /todos:
    get:
      summary: Returns all todos
      operationId: getTodos
      tags:
        - todos
      responses:
        '200':
          description: Succesful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  todos:
                    type: array
                      items:
                        $ref: '#/components/schemas/Todo'
    post:
      summary: Creates a new todo
      operationId: createTodo
      tags:
        - todos
      requestBody:
        description: Todo object that needs to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '200':
          description: Succesful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
  
  /todos/{id}:
    get:
      summary: Returns a todo by id
      operationId: getTodoById
      tags:
        - todos
      parameters:
        - name: id
          in: path
          description: ID of todo to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Succesful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found

    
    put:
      summary: Updates a todo
      operationId: updateTodo
      tags:
        - todos
      parameters:
        - name: id
          in: path
          description: ID of todo to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Todo object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '200':
          description: Succesful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found

          
    delete:
      summary: Deletes a todo
      operationId: deleteTodo
      tags:
        - todos
      parameters:
        - name: id
          in: path
          description: ID of todo to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Succesful response
        '404':
          description: Todo not found






